apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-root
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/sycanz/devsecops-gitops.git
      targetRevision: main
      path: apps/shared
    - repoURL: https://github.com/sycanz/devsecops-gitops.git
      targetRevision: main
      path: apps/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
